# Generated by Django 5.2.7 on 2026-04-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
                ('foi_postado', models.BooleanField(default=True)),
            ],
        ),
    ]
