# Generated by Django 5.2.7 on 2026-04-27 20:52

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    used = set()
    for post in Post.objects.all().order_by('pk'):
        base = slugify(post.titulo) or f'post-{post.pk}'
        slug = base
        counter = 1
        while slug in used or Post.objects.filter(slug=slug).exclude(pk=post.pk).exists():
            slug = f'{base}-{counter}'
            counter += 1
        post.slug = slug
        used.add(slug)
        post.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
